version: '3'

services:
  admin:
    image: admin
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    ports:
      - '8081:8080'
    volumes:
      - ./admin:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - api
  api:
    image: api-v2
    platform: linux/amd64
    build:
      context: ./api/v2
      dockerfile: Dockerfile
    entrypoint: ["/app/docker-entrypoint.sh"]
    env_file:
      - ./api/v2/.env
    environment:
      TZ: Asia/Tokyo
      DATABASE_URL: /app/db/database.sqlite3
      AWS_ACCESS_KEY_ID: ${MINIO_ACCSES_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}
    ports:
      - '8080:8080'
    # depends_on:
    #   storage:
    #     condition: service_healthy
  storage:
    image: minio/minio:latest
    ports:
      - 9001:9001
    volumes:
      - miniostorage:/data
    command:
      server /data --console-address ":9001"
    environment:
      - MINIO_ACCESS_KEY_ID
      - MINIO_SECRET_ACCESS_KEY
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 5s

volumes:
  node_modules:
  miniostorage:

networks:
  default:
    name: calendar
