version: '3'

services:
  admin:
    image: admin
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    ports:
      - '8081:8080'
    volumes:
      - ./admin:/usr/src/app
      - node_modules:/usr/src/app/node_modules
  api:
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command:
      rails s -b 0.0.0.0
    volumes:
      - ./api:/rails
    env_file:
      - ./api/.env
    ports:
      - '3000:3000'

volumes:
  node_modules:
