version: '3'

services:
  api:
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command:
      rails s -b 0.0.0.0
    volumes:
      - ./api:/rails
    env_file:
      - ./api/.env
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=umineco_calendar
    ports:
      - 5432:5432
