version: '3'

services:
  admin:
    image: admin
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - '8081:80'
    volumes:
      - ./admin/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./admin/nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf:ro
    depends_on:
      - api
  api:
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      AWS_ACCESS_KEY_ID: ${MINIO_ACCSES_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}
      DATABASE_URL: sqlite3:db/litestream/database.sqlite3
    ports:
      - '3000:3000'
  storage:
    image: minio/minio:latest
    ports:
      - 9001:9001
    volumes:
      - miniostorage:/data
    command:
      server /data --console-address ":9001"
    environment:
      - MINIO_ACCESS_KEY_ID
      - MINIO_SECRET_ACCESS_KEY
  storage_ctl:
    image: minio/mc:latest
    volumes:
      - ./storage-setup.sh:/storage-setup.sh:ro
    environment:
      - MINIO_ACCESS_KEY_ID
      - MINIO_SECRET_ACCESS_KEY
    # docker-compose run から動かすことを想定しているので何もしない
    entrypoint: ["/bin/sh"]

volumes:
  miniostorage:

networks:
  default:
    name: calendar
