version: '3'

services:
  admin:
    image: admin
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    ports:
      - '8081:8080'
    volumes:
      - ./admin:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - api
  api:
    image: api
    build:
      context: ./api/v2/
      dockerfile: Dockerfile
    env_file:
      - ./api/v2/.env
    environment:
      TZ: Asia/Tokyo
      AWS_ACCESS_KEY_ID: ${MINIO_ACCSES_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}
    ports:
      - '3000:8080'
  storage:
    image: minio/minio:latest
    ports:
      - 9001:9001
    volumes:
      - miniostorage:/data
    command:
      server /data --console-address ":9001"
    environment:
      - MINIO_ACCESS_KEY_ID
      - MINIO_SECRET_ACCESS_KEY

volumes:
  node_modules:
  miniostorage:

networks:
  default:
    name: calendar
