name: Build container image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag to build and push'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          - admin
          - api

    steps:
      - name: Set image tag
        id: tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "::set-output name=version::${{ github.event.inputs.version }}"
          else
            echo "::set-output name=version::${GITHUB_REF#refs/tags/}"
          fi

      - uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ steps.tag.outputs.version }}

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: windyakin
          password: ${{ secrets.GHCR_TOKEN }}

      - uses: docker/login-action@v3
        with:
          username: windyakin
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.app }}
          file: ./${{ matrix.app }}/Dockerfile
          tags: |
            ghcr.io/numazu-umineco/calendar-${{ matrix.app }}:${{ steps.tag.outputs.version }}
            windyakin/umineco-calendar-${{ matrix.app }}:${{ steps.tag.outputs.version }}
          push: true
